threedpdr – 3D-PDR
threedpdr Program
160 statements
Source File
Uses
healpix_types
maincode_module
global_module
healpix_module
definitions
chemistry_module
maincode_local
uclpdr_module
Calls
Variables
Type Attributes Name Initial
real(kind=dp) :: thfpix
real(kind=dp) :: phfpix
Call graph
threedpdr calls allocations, calc_columndens, calc_crattenuation, calc_uvfield, changetemperature, checkconvergence, chemicaliterations, coolingfunctions, evaluation_points, initialization, mk_xy2pix, pix2ang_nest, pix2vec_nest, read_command_line, read_rates, read_species, readcoolants, readdensity, readparams, writeoutputs