! Calculate the partition function for the given species
SUBROUTINE CALCULATE_PARTITION_FUNCTION(PARTITION_FUNCTION,NLEV,ENERGIES,WEIGHTS,TEMPERATURE)

      USE HEALPIX_TYPES
      IMPLICIT NONE

      INTEGER(KIND=I4B), INTENT(IN) :: NLEV
      REAL(KIND=DP), INTENT(IN)     :: ENERGIES(1:NLEV),WEIGHTS(1:NLEV)
      REAL(KIND=DP), INTENT(IN)     :: TEMPERATURE
      REAL(KIND=DP), INTENT(OUT)    :: PARTITION_FUNCTION

      INTEGER(KIND=I4B) :: ILEVEL

      PARTITION_FUNCTION=0.0D0
      DO ILEVEL=1,NLEV
         PARTITION_FUNCTION=PARTITION_FUNCTION + WEIGHTS(ILEVEL)*EXP(-ENERGIES(ILEVEL)/KB/TEMPERATURE)
      ENDDO

RETURN
END SUBROUTINE CALCULATE_PARTITION_FUNCTION

